config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/index', to: 'home#index'

  # Маршруты для пользователей
  get 'users/index', to: 'users#index'
  post 'users/index', to: 'users#create'
  get 'users/:id', to: 'users#destroy', as: :deleteUser

  resources :users, only: [:index, :create, :index, :destroy] do
    member do
      get 'profile' # Доступ к профилю конкретного пользователя
    end
  end

  # Маршруты для сессий
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: :logout
  delete 'logout', to: 'sessions#destroy'


  # Маршруты для желаний
  get '/wishes/new', to: 'wishes#new', as: :wishes
  post '/wishes/new', to: 'wishes#create', as: :wishes_new
  get '/wishes/:id', to: 'wishes#show', as: :showWish
  get '/wishes/:id/edit', to: 'wishes#edit', as: :editWish
  put '/wishes/:id', to: 'wishes#update', as: :wish
  get '/wishes/:id', to: 'wishes#destroy', as: :deleteWish
  patch '/wishes/:id', to: 'wishes#update', as: :wish_update
  delete '/wishes/:id', to: 'wishes#destroy'

  resources :wishes do
    member do
      post 'fulfill'  # добавляем маршрут для выполнения желания
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fulfillment.rb
class Fulfillment < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  belongs_to :performer, class_name: 'User'
  belongs_to :wish
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :login, presence: true
  has_secure_password :password, validations: true
  has_many :wishes, dependent: :destroy

  has_many :created_wishes, class_name: 'Wish', foreign_key: 'user_id'
  has_many :fulfillments, foreign_key: 'creator_id'
  has_many :fulfilled_wishes, through: :fulfillments, source: :wish

  has_many :fulfillments_as_creator, class_name: 'Fulfillment', foreign_key: 'creator_id'
  has_many :fulfillments_as_performer, class_name: 'Fulfillment', foreign_key: 'performer_id'
  has_many :fulfilled_wishes_as_creator, through: :fulfillments_as_creator, source: :wish
  has_many :fulfilled_wishes_as_performer, through: :fulfillments_as_performer, source: :wish

  def destroy
    super
  end
end

app/models/wish.rb
class Wish < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  has_one :fulfillment
  def destroy
    super
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :user_signed_in?
  before_action :set_current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    redirect_to root_path, alert: "You must be logged in to access this section." unless current_user
  end

  def user_signed_in?
    !!current_user
  end

  private
  def set_current_user
    user = User.find_by(id: session[:user_id])
    if user.nil?
      @current_user = user
    else
      @current_user = user if session[:user_id]
    end
  end

  def destroy_session
    session[:user_id] = nil
    cookies.delete(:remember_token) if cookies[:remember_token]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def   index
    @wishes = Wish.includes(:user).all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user&.authenticate(params[:password]) # Проверка пароля
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully logged in"
    else
      flash[:error] = "Такого пользователя не существует!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Successfully logged out"
  end
end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_current_user, only: [:profile, :destroy] # Добавляем profile в before_action

  def index
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Registration completed. You are now logged in." # Перенаправляем на профиль
    else
      flash[:error1] = "Такой пользователь уже существует!"
      redirect_to users_index_path
    end
  end



  def profile
    @user = @current_user # Передаем текущего пользователя в представление
    @fulfillments = Fulfillment.where(performer_id: @user.id)
  end


  def destroy
    if @current_user.destroy
      session[:user_id] = nil
      redirect_to root_path, notice: 'Аккаунт успешно удален.'
    else
      redirect_to profile_user_path(@current_user), alert: 'Возникла ошибка при удалении аккаунта'
    end
  end

  private

  def set_current_user
    user = User.find_by(id: session[:user_id])
    if user.nil?
      redirect_to root_path
    else
      @current_user = user if session[:user_id]
    end
  end

  def user_params
    params.require(:user).permit(:login, :email, :password)
  end
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :set_wish, only: [:show, :edit, :update, :destroy, :fulfill]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @wishes = Wish.all.includes(:user)
  end

  def new
    @wish = Wish.new
  end

  def create
    @wish = current_user.wishes.build(wish_params)

    if @wish.save
      redirect_to profile_user_path(@current_user), notice: "Wish created successfully."

    else
      render :index
    end
  end

  def show
  end

  def edit
  end

  def update
    if @wish.update(wish_params)
      redirect_to profile_user_path(@current_user), notice: "Wish updated successfully."
    else
      render :edit
    end
  end

  def destroy
    if @wish.user == current_user # Проверяем, что пользователь является владельцем пожелания
      @wish.destroy
      redirect_to profile_user_path(@current_user), notice: 'Пожелание успешно удалено.'
    else
      redirect_to profile_user_path(@current_user), alert: 'Вы не можете удалить это пожелание.'
    end
  end

  def fulfill
    @wish = Wish.find(params[:id])
    @fulfillment = @wish.build_fulfillment
    @fulfillment.creator_id = @wish.user_id
    @fulfillment.performer_id = @current_user.id
    if @fulfillment.save
      redirect_to root_path, notice: "Fulfillment created successfully."
    else
      render profile_user_path(@current_user), alert: "Failed to create fulfillment."
    end
  end

  private

  def set_wish
    @wish = Wish.find(params[:id])
  end

  def wish_params
    params.require(:wish).permit(:title, :description)
  end

  def authenticate_user!
    redirect_to root_path, alert: "You must be logged in to access this section." unless session[:user_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/index.html.erb
<div id="main-page" class="container hidden">
<h2>Карточки желаний</h2><br>
  <% if user_signed_in? %>
    <% if @current_user %>
      <div id="wish-card-container">
        <% @wishes.each do |wish| %>
          <div class="wish-card">
            <h3><%= wish.title %></h3>
            <p><%= wish.description %></p>

            <% if wish.user.id == @current_user.id %>
              <p>Это ваше желание</p><br>
            <% else %>
              <p>Создано пользователем: <%= wish.user.login %></p><br>
            <% end %>

            <% if Fulfillment.exists?(wish_id: wish.id) %>
              <% user = User.find_by(id: Fulfillment.find_by(wish_id: wish.id).performer_id)  %>
              <p>Выполнено пользователем: <%= user.login %></p>
            <% else %>
              <% if wish.user.id != @current_user.id %>
                <%= button_to 'Ометить выполненным', fulfill_wish_path(wish), method: :post, class: "btn"  %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <h3>Чтобы посмотреть, что загадали другие пользователи, необходимо войти или зарегистрироваться</h3>
  <% end %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<html>
  <head>
    <title><%= content_for(:title) || "Projectweb" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

  </head>

  <body>
  <nav class="navbar">
    <div class="brand">
      <h1>Wish Cards</h1>
    </div>
    <div class="nav-links">
      <%= link_to "На главную", home_index_path %>
      <% if user_signed_in? %>
        <% if @current_user %>
          <a><%= link_to "Личный кабинет", profile_user_path(@current_user) %></a>
          <a><%= link_to "Выйти", logout_path, method: :delete %></a>
        <% end %>
      <% else %>
        <a><%= link_to "Регистрация", users_index_path %></a>
        <a><%= link_to "Войти", login_path %></a>
      <% end %>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<div id="register-page" class="container hidden">
  <div class="auth-form" id="register-form">
    <%= form_for(@user, url: users_index_url) do |f| %>
      <h2>Регистрация</h2><br>

      <% if flash[:error1] %>
        <div class="alert alert-danger" id="error_message">
          <%= flash[:error1] %>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label "Логин" %>
        <%= f.text_field :login, class: "form-control", required: true %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control", required: true %>
      </div>

      <div class="form-group">
        <%= f.label "Пароль" %>
        <%= f.password_field :password, class: "form-control", required: true %>
      </div>

      <div class="form-group">
        <%= f.label "Введите пароль ещё раз" %>
        <%= f.password_field :password_conf, class: "form-control", required: true %>
      </div>

      <%= f.submit "Зарегистрироваться", class: "btn", type: "submit" %>
    <% end %>
    <br><p>Уже есть аккаунт?</p>
    <br><%= link_to "Войти", login_path, class: "btn" %>
  </div>
  <script>
      $(document).ready(function() {
          // Удаляем сообщение об ошибке через 5 секунд
          setTimeout(function() {
              $("#error_message").fadeOut();
          }, 5000); // Время в миллисекундах (5 секунд)
      });
  </script>
</div>

app/views/users/profile.html.erb
<div id="account-page" class="container hidden">
  <h2>Личный кабинет</h2>
  <h3>Пользователь: <i><%= @user.login %></i></h3><br>
  <%= link_to "Создать новое желание", wishes_path, class: "btn" %><br><br>

  <div id="my-wishes-container">
    <br><h3>Мои желания</h3>
    <br><% @user.wishes.each do |wish| %>
      <div class="wish-card">
        <h3><%= wish.title %></h3>
        <p><%= wish.description %></p>
        <% if Fulfillment.exists?(wish_id: wish.id) %>
          <p>Выполнено пользователем: <%= User.find_by(id: Fulfillment.find_by(wish_id: wish.id).performer_id).login %></p>
        <% end %>
        <br><%= link_to 'Просмотр', showWish_path(wish), class: "btn" %>
      </div>
    <% end %>
  </div>

  <div id="performed-wishes-container">
    <br><h3>Желания, выполненные мной</h3><br>
    <% if @fulfillments.any? %>
      <% @fulfillments.each do |fulfillment| %>

        <% wish = Wish.find_by(id: fulfillment.wish_id)%>
          <div class="wish-card">
            <% if !wish.nil? %>
                <h3><%= wish.title %></h3>
                <p><%= wish.description %></p>
                <p>Создано пользователем: <%= User.find_by(id: wish.user_id).login %></p><br>
            <% end %>
          </div>
      <% end %>
    <% end %>
  </div>

  <a href="#" class="btn btn-delete" id="delete-btn">Удалить аккаунт</a>
</div>

<div id="delete-modal" style="display:none;">
  <div class="modal-content">
    <span class="close" id="close-modal">&times;</span>
    <p>Вы уверены, что хотите удалить аккаунт?</p><br>
    <div class="button-container">
      <%= form_with(url: deleteUser_path(@user), method: :delete, local: true, id: "confirm-delete-form") do %>
        <%= submit_tag 'Да, удалить', class: "btn btn-delete" %>
      <% end %>
      <button class="btn" id="cancel-delete">Отмена</button>
    </div>
  </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const deleteBtn = document.getElementById("delete-btn");
        const modal = document.getElementById("delete-modal");
        const closeModal = document.getElementById("close-modal");
        const cancelDelete = document.getElementById("cancel-delete");

        // Открытие модального окна
        deleteBtn.onclick = function() {
            modal.style.display = "block";
        }

        // Закрытие модального окна при нажатии на "x"
        closeModal.onclick = function() {
            modal.style.display = "none";
        }

        // Закрытие модального окна при нажатии на кнопку "Отмена"
        cancelDelete.onclick = function() {
            modal.style.display = "none";
        }

        // Закрытие модального окна при клике вне его содержимого
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    });
</script>

app/views/wishes/edit.html.erb
<div id="wish-form-update" class="container hidden">
  <div class="auth-form" id="update-wish-form">
    <h2>Редактирование желания</h2><br>

    <%= form_with(model: @wish, local: true) do |form| %>
      <% if @wish.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@wish.errors.count, "error") %> prohibited this wish from being saved:</h2>
          <ul>
            <% @wish.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label "Название" %>
        <%= form.text_field :title %>
      </div>

      <div class="form-group">
        <%= form.label "Описание" %>
        <%= form.text_area :description %>
      </div>

      <%= form.submit "Обновить", class: "btn", type: "submit" %>
    <% end %>
    <br><%= link_to 'Назад', profile_user_path(@current_user), class: "btn" %>
  </div>
</div>

app/views/wishes/index.html.erb
<h1>Wishes</h1>
<%= link_to 'Новое пожелание', new_wish_path %>

<ul>
  <% @wishes.each do |wish| %>
    <li>
      <strong><%= wish.title %></strong> by <%= wish.user.login %><br>
      <%= wish.description %><br>
      <%= link_to 'Просмотр', wish_path(wish) %> |
      <%= link_to 'Редактировать', edit_wish_path(wish) %> |
      <%= form_with(url: delWish_path(wish), method: :delete, local: true) do %>
        <br><%= submit_tag 'Удалить', data: { confirm: 'Вы уверены, что хотите удалить это пожелание?' }, class: "btn" %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/wishes/new.html.erb
<div id="wish-form" class="container hidden">
  <div class="auth-form" id="create-wish-form">
    <h2>Новое желание</h2><br>

    <%= form_with(model: @wish, local: true) do |form| %>
      <% if @wish.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

          <ul>
            <% @wish.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label "Название" %>
        <%= form.text_field :title %>
      </div>

      <div class="form-group">
        <%= form.label "Описание" %>
        <%= form.text_area :description %>
      </div>

      <%= form.submit "Создать", class: "btn", type: "submit"%>
    <% end %>
    <br><%= link_to 'Назад', profile_user_path(@current_user), class: "btn" %>
  </div>
</div>

app/views/wishes/show.html.erb
<div id="wish-card">
  <div class="wish-card">
    <h3><%= @wish.title %></h3>
    <p><%= @wish.description %></p>
    <p>Создано пользователем: <%= @wish.user.login %></p>
    <% if Fulfillment.exists?(wish_id: @wish.id) %>
      <p>Выполнено пользователем: <%= User.find_by(id: Fulfillment.find_by(wish_id: @wish.id).performer_id).login %></p>
    <% end %>
  </div>
  <% if !Fulfillment.exists?(wish_id: @wish.id) %>
    <%= link_to 'Редактировать', editWish_path(@wish), class: "btn"  %>
  <% end %>
  <%= link_to 'Назад', profile_user_path(@current_user), class: "btn" %>
  <a href="#" class="btn btn-delete" id="delete-btn">Удалить</a>
</div>

<div id="delete-modal" style="display:none;">
  <div class="modal-content">
    <span class="close" id="close-modal">&times;</span>
    <p>Вы уверены, что хотите удалить это пожелание?</p><br>
    <div class="button-container">
      <%= form_with(url: deleteWish_path(@wish), method: :delete, local: true, id: "confirm-delete-form") do %>
        <%= submit_tag 'Да, удалить', class: "btn btn-delete" %>
      <% end %>
      <button class="btn" id="cancel-delete">Отмена</button>
    </div>
  </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const deleteBtn = document.getElementById("delete-btn");
        const modal = document.getElementById("delete-modal");
        const closeModal = document.getElementById("close-modal");
        const cancelDelete = document.getElementById("cancel-delete");

        // Открытие модального окна
        deleteBtn.onclick = function() {
            modal.style.display = "block";
        }

        // Закрытие модального окна при нажатии на "x"
        closeModal.onclick = function() {
            modal.style.display = "none";
        }

        // Закрытие модального окна при нажатии на кнопку "Отмена"
        cancelDelete.onclick = function() {
            modal.style.display = "none";
        }

        // Закрытие модального окна при клике вне его содержимого
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    });
</script>